
#config create table in database when run application
spring:
  batch:
    jdbc:
      initialize-schema: always
#    job:
#      enabled: false #disable auto run job when run application

  #config for database
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# init database from sql file schema
  sql:
    init:
      mode: always
